name: portainer
version: git
summary: portainer
description: |
  Portainer is a powerful, open source toolset that allows you
  to easily build and manage containers in Docker, Docker Swarm, Kubernetes and Azure ACI.

base: core22
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

environment:
  PATH: $SNAP/docker/bin:$PATH

plugs:
  docker-executables:
    interface: content
    content: docker-executables
    target: $SNAP/docker
    default-provider: docker

apps:
  container:
    command: bin/run.sh
    daemon: simple
    plugs:
      - docker
      - docker-executables

parts:
  overlay:
    plugin: dump
    source: overlay
